[tool.poetry]
name = "poseidon_viz"
version = "0.1.0"
description = ""
authors = ["Panos Mavrogiorgos <pmav99@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
pyproj = "^3.0.0"
holoviews = "^1.14.0"
numpy = "^1.19.4"
pandas = "^1.1.5"
bokeh = "^2.2.3"
panel = "^0.10.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
