[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "thalassa"
version = "0.1.0"
description = "Visualization of large scale results of hydrodynamic simulations"
authors = [
  "Panos Mavrogiorgos <pmav99@gmail.com>",
  "George Breyiannis <George.BREYIANNIS@ec.europa.eu>",
]
readme = "README.md"
homepage = "https://github.com/brey/Thalassa"
keywords = [
    "Hydrodynamic",
    "Sea",
    "Simulation",
    "Visualization",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: End Users/Desktop",
    "Intended Audience :: Science/Research",
    'License :: OSI Approved :: European Union Public Licence 1.2 (EUPL 1.2)',
    "Operating System :: MacOS",
    "Operating System :: POSIX :: Linux",
    #'Operating System :: OS Independent',
    "Programming Language :: Python :: 3",
    'Topic :: Scientific/Engineering :: Atmospheric Science',
    "Topic :: Scientific/Engineering :: GIS",
    "Topic :: Scientific/Engineering :: Hydrology",
    "Topic :: Scientific/Engineering :: Visualization",
]


[tool.poetry.dependencies]
python = "^3.8"
pyproj = "^3.0.0"
holoviews = "^1.14.0"
numpy = "^1.19.4"
pandas = "^1.1.5"
bokeh = "^2.2.3"
panel = "^0.10.2"
typer = "^0.3.2"
xarray = "^0.16.2"
netCDF4 = "^1.5.5"
geoviews = "^1.8.1"
scipy = "^1.5.4"
datashader = "^0.11.1"
matplotlib = "^3.3.3"
llvmlite = "<=0.34"
hvplot = "^0.7.0"
noaa-coops = "^0.1.9"
PyQt5 = "^5.15.4"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
ipython = "^7.20.0"
jedi = "<0.18"

[tool.poetry.scripts]
thalassa = "thalassa.cli:app"

[tool.black]
line-length = 129
target-version = ['py38']
