name: Thalassa
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - geos
  - python=3.8
  - proj < 8
  - gdal=3.2.1
  - jupyter-server-proxy
  - bash_kernel
  - hvplot
  - datashader
  - matplotlib
  - xarray
  - zarr
  - pandas
  - geoviews
  - typer
